// Builds the English trigram table Mantis scores against. Run `npm run trigrams`.
//
// Input is a quadgram census: 456,976 lines of "QUAD count", one per cell, from
// counting a corpus of ordinary English prose. Trigram counts fall out of it by
// summing over the fourth letter, which loses one trigram per contiguous run of
// text and is otherwise exact.
//
// Why trigrams and not the quadgrams themselves. The census behind this table
// holds ~2.5M quadgrams. Spread over 456,976 quadgram cells that is five
// observations each, which is noise; spread over 17,576 trigram cells it is
// ~142 each, which is an estimate. Measured against held-out English the
// trigram table hits 99.1% of positions and the quadgram table 96.0%, and it
// packs to 17KB rather than 246KB. The smaller model is also the better one.
//
// The output is committed as text so the numbers can be read and checked.
// build.rs packs it to a dense byte table at compile time.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'trawl-core', 'src', 'mantis', 'ngram', 'trigrams.txt');

const source = process.argv[2];
if (!source) {
	console.error('usage: node fixtures/trigrams.mjs <quadgram-census.txt>');
	console.error('expects lines of "QUAD count", 456976 of them.');
	process.exit(1);
}

const counts = new Map();
let quadgrams = 0;
let cells = 0;

for (const line of readFileSync(resolve(source), 'utf8').split('\n')) {
	const space = line.indexOf(' ');
	if (space !== 4) continue;

	const count = Number(line.slice(space + 1).trim());
	if (!Number.isFinite(count) || count <= 0) continue;

	const quad = line.slice(0, 4).toUpperCase();
	if (!/^[A-Z]{4}$/.test(quad)) continue;

	const tri = quad.slice(0, 3);
	counts.set(tri, (counts.get(tri) ?? 0) + count);
	quadgrams += count;
	cells++;
}

if (counts.size === 0) {
	console.error(`no usable quadgrams in ${source}. Every count may be zero.`);
	process.exit(1);
}

const sorted = [...counts].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
const total = sorted.reduce((n, [, c]) => n + c, 0);

const header = [
	'# English trigram counts, derived from a quadgram census of ordinary prose.',
	'# Generated by fixtures/trigrams.mjs — do not hand-edit.',
	`# ${sorted.length} of 17576 cells observed, ${total} trigrams counted.`,
	''
].join('\n');

writeFileSync(OUT, header + sorted.map(([t, c]) => `${t} ${c}`).join('\n') + '\n');

console.log(`read    ${cells} nonzero quadgram cells, ${quadgrams} quadgrams`);
console.log(
	`wrote   ${sorted.length} trigrams (${((sorted.length / 17576) * 100).toFixed(1)}% of cells), ${total} counted`
);
console.log(
	`top     ${sorted
		.slice(0, 8)
		.map(([t]) => t)
		.join(' ')}`
);
console.log(`        ${OUT}`);
